### ISSUE TITLE
PFDateFormatter Class Issue

### ISSUE THREAD

**Issue by pranjalsatija** [ParsePlatform/Parse-SDK-iOS-OSX#245] opened 2015-09-12 20:32 UTC
In  `PFDateFormatter`'s dateFromString method in the iOS SDK, the accepted parameter is an NSString, but this function is occasionally called with an NSDate. For now, I've fixed it with the following: `    if ([string class] == NSClassFromString(@"__NSDate")) {
        return string;
    }`

But this bug took a while to figure out, please fix it.

**Comment by nlutsenko** [comment] 2015-09-12 20:34
Duplicate of #243, fix is already there, merging in soon and going to be avaialble in the next version of the SDK.

**Closed by nlutsenko** 2015-09-12 20:34 UTC
Labels: duplicate
