### ISSUE TITLE
Parse 1.8.0 is converting Bool into Numbers

### ISSUE THREAD

**Issue by cikpis** [ParsePlatform/Parse-SDK-iOS-OSX#27] opened 2015-08-16 18:05 UTC
Hi guys, 

I am having problems with BOOL in iOS. Parse is converting them into Numbers. This started happening on 1.8.0 of parse SDK. How can I fix it?

Thanks in advance,
Carmelo

**Comment by richardjrossiii** [comment] 2015-08-16 18:06
Duplicate of #13. Will be fixed in 1.8.1.

**Comment by nlutsenko** [comment] 2015-08-16 18:07
Hey @cikpis , it was already fixed in #21 and merged into master.
This is indeed a bug introduced in 1.8.0 - feel free to simply start using the master of the SDK.

**Closed by richardjrossiii** 2015-08-16 18:06 UTC

**Comment by cikpis** [comment] 2015-08-16 18:09
Thanks guys for the quickly response. BTW, do you know when parse 1.8.1 release is scheduled? I was just sending the app to Apple Review Process :)

**Comment by nlutsenko** [comment] 2015-08-16 18:11
We don't have a specific date yet, but since master additions are pretty minimal at this point - it's stable to use the SDK from master.

**Comment by cikpis** [comment] 2015-08-16 18:13
You mean to use the follow code in Podfile?

pod 'Parse', :git => "https://github.com/parseplatform/parse-sdk-iOS-OSX.git"

**Comment by nlutsenko** [comment] 2015-08-16 18:15
Yup. ^ that should work.

**Comment by cikpis** [comment] 2015-08-16 18:18
Yep it works. Thanks!

Cheers!
