### ISSUE TITLE
Could Parse support iOS6?

### ISSUE THREAD

**Issue by mrFranklin** [ParsePlatform/Parse-SDK-iOS-OSX#496] opened 2015-10-31 03:06 UTC
Could Parse support iOS 6 again?
our develpoing app(a game) must support the iOS6 now.
if I use 1.7.5, it looks like not suppot iOS9.

**Comment by nlutsenko** [comment] 2015-10-31 04:37
Closing as duplicate of #493.

**Closed** 2015-11-02 04:32 UTC
Labels: duplicate
