### ISSUE TITLE
[query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) with iOS 7

### ISSUE THREAD

**Issue by marian19** [ParsePlatform/Parse-SDK-iOS-OSX#449] opened 2015-10-22 11:34 UTC
when i try to use [query findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) with iOS 7 , it always returns this error " nserror * domain @ nscocoaerrordomain - code 3840"

**Comment by drewlarsen** [comment] 2015-10-22 16:16
I think is probably a duplicate of the error I filed yesterday:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/448

**Closed** 2015-10-22 20:10 UTC
Labels: duplicate

**Comment by nlutsenko** [comment] 2015-10-22 20:27
Duplicate of #448, indeed.
