### ISSUE TITLE
Twitter login problem occured on my 4 app last 2 days

### ISSUE THREAD

**Issue by nahitheper** [ParsePlatform/Parse-SDK-iOS-OSX#808] opened 2016-02-03 16:17 UTC
We are using twitter login protocols on parse in our app's login scenes. In the last 2 days we got an error in login process.
We use 
 PFTwitterUtils.logInWithBlock({ (user: PFUser?, error: NSError?) -> Void in

User cannot login or cannot be generated on the User class. 
and got this error:
Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.}
I've found same problem which is here
http://stackoverflow.com/questions/35173315/twitter-connect-always-fail-on-parse-sdk

Can you help us to answer that: is there a problem with twitter API or parse servers ? 
Thanks.

**Comment by nlutsenko** [comment] 2016-02-04 07:27
Sorry for the delay on responding here...
We identified the root cause approximately 7 hours ago and rolled out a fix for this on the backend.
Please let me know if this is still a problem for you.

**Closed by nlutsenko** 2016-02-04 07:27 UTC
