### ISSUE TITLE
Randomly occuring `PFMD5HashFromData` Crash

### ISSUE THREAD

**Issue by radiovisual** [ParsePlatform/Parse-SDK-iOS-OSX#266] opened 2015-09-15 17:34 UTC
I am using Parse to build an iOS app, and I get an **extremely frustrating** error that never gives me anything useful in the backtrace, and it only randomly occurs as my app is running. Sometimes it happens, sometimes it doesn't, but when I am testing the app, **I test under the exact same conditions each time, and I do the same things each time**, but even though every thing is the same each time, there is nothing I can do to manually recreate the problem. 

The clue you might be interested in, is the problem only happens when I run the app on an iPhone 4S (iOS 7.1.2), but it never seems to happen when I run on an iPod Touch (5th generation, iOS 7.1.2)

Here are the Parse Frameworks I am using (via cocoapods):

```
Using Bolts (1.2.2)
Using Facebook-iOS-SDK (3.24.0)
Using Parse (1.8.3)
Using ParseCrashReporting (1.8.3)
Using ParseFacebookUtils (1.8.3)
Using ParseUI (1.1.6)
```

**Below is the entire backtrace from the lldb debugger :**

*(frames 79 - 6012) are omitted for length)*

```
* thread #27: tid = 0x3a556, 0x39de23e4 libsystem_c.dylib`__vfprintf + 28, queue = 'com.apple.root.default-priority', stop reason = EXC_BAD_ACCESS (code=2, address=0x51b1dec)
    frame #0: 0x39de23e4 libsystem_c.dylib`__vfprintf + 28
    frame #1: 0x39df82c6 libsystem_c.dylib`__v2printf + 374
    frame #2: 0x39da723c libsystem_c.dylib`_vsnprintf + 348
    frame #3: 0x39da7b2c libsystem_c.dylib`vsnprintf_l + 32
    frame #4: 0x39da7b06 libsystem_c.dylib`snprintf_l + 22
    frame #5: 0x2f0a19d0 CoreFoundation`__CFStringAppendFormatCore + 8464
    frame #6: 0x2f010610 CoreFoundation`_CFStringCreateWithFormatAndArgumentsAux + 76
    frame #7: 0x2f9e8162 Foundation`-[NSPlaceholderString initWithFormat:locale:arguments:] + 130
    frame #8: 0x2f9e8068 Foundation`+[NSString stringWithFormat:] + 60
  * frame #9: 0x0025b4e0 myApp`PFMD5HashFromData(data=0x1573a6c0) + 412 at PFHash.m:63
    frame #10: 0x00261e42 myApp`-[PFJSONCacheItem initWithObject:](self=0x1573a580, _cmd=0x31facc39, object=0x157143d0) + 286 at PFInternalUtils.m:286
    frame #11: 0x0026200a myApp`+[PFJSONCacheItem cacheFromObject:](self=0x0066d0c8, _cmd=0x00517cb3, object=0x157143d0) + 74 at PFInternalUtils.m:300
    frame #12: 0x002726d8 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518dd1, object=0x157143d0, key=0x005d72e8) checkForChangesToMutableContainer:forKey:] + 424 at PFObject.m:713
    frame #13: 0x00272b6e myApp`__55-[PFObject(.block_descriptor=0x051b3954, key=0x005d72e8, obj=0x157143d0, stop=0x051b38ec) checkForChangesToMutableContainers]_block_invoke + 222 at PFObject.m:731
    frame #14: 0x2f059eca CoreFoundation`__65-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 54
    frame #15: 0x2f04d1a2 CoreFoundation`-[__NSDictionaryI enumerateKeysAndObjectsWithOptions:usingBlock:] + 182
    frame #16: 0x002729dc myApp`-[PFObject(self=0x169a0310, _cmd=0x00518d6a) checkForChangesToMutableContainers] + 412 at PFObject.m:729
    frame #17: 0x00271bf0 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 164 at PFObject.m:656
    frame #18: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169a0310, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #19: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b3c70, key=0x005cdcc8, obj=0x169a0310, stop=0x051b3be8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #20: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #21: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #22: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x16937f70, _cmd=0x31f2560c, block=0x051b3c70) + 82 at PFObjectEstimatedData.m:59
    frame #23: 0x00271d24 myApp`-[PFObject(self=0x169c3ec0, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #24: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169c3ec0, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #25: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b3e70, key=0x005cd5e8, obj=0x169c3ec0, stop=0x051b3de8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #26: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #27: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #28: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x169e8460, _cmd=0x31f2560c, block=0x051b3e70) + 82 at PFObjectEstimatedData.m:59
    frame #29: 0x00271d24 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #30: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169a0310, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #31: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b4070, key=0x005cdcc8, obj=0x169a0310, stop=0x051b3fe8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #32: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #33: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #34: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x16937f70, _cmd=0x31f2560c, block=0x051b4070) + 82 at PFObjectEstimatedData.m:59
    frame #35: 0x00271d24 myApp`-[PFObject(self=0x169c3ec0, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #36: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169c3ec0, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #37: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b4270, key=0x005cd5e8, obj=0x169c3ec0, stop=0x051b41e8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #38: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #39: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #40: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x169e8460, _cmd=0x31f2560c, block=0x051b4270) + 82 at PFObjectEstimatedData.m:59
    frame #41: 0x00271d24 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #42: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169a0310, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #43: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b4470, key=0x005cdcc8, obj=0x169a0310, stop=0x051b43e8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #44: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #45: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #46: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x16937f70, _cmd=0x31f2560c, block=0x051b4470) + 82 at PFObjectEstimatedData.m:59
    frame #47: 0x00271d24 myApp`-[PFObject(self=0x169c3ec0, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #48: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169c3ec0, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #49: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b4670, key=0x005cd5e8, obj=0x169c3ec0, stop=0x051b45e8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #50: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #51: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #52: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x169e8460, _cmd=0x31f2560c, block=0x051b4670) + 82 at PFObjectEstimatedData.m:59
    frame #53: 0x00271d24 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #54: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169a0310, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #55: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b4870, key=0x005cdcc8, obj=0x169a0310, stop=0x051b47e8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #56: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #57: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #58: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x16937f70, _cmd=0x31f2560c, block=0x051b4870) + 82 at PFObjectEstimatedData.m:59
    frame #59: 0x00271d24 myApp`-[PFObject(self=0x169c3ec0, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #60: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169c3ec0, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #61: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b4a70, key=0x005cd5e8, obj=0x169c3ec0, stop=0x051b49e8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #62: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #63: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #64: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x169e8460, _cmd=0x31f2560c, block=0x051b4a70) + 82 at PFObjectEstimatedData.m:59
    frame #65: 0x00271d24 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #66: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169a0310, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #67: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b4c70, key=0x005cdcc8, obj=0x169a0310, stop=0x051b4be8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #68: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #69: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #70: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x16937f70, _cmd=0x31f2560c, block=0x051b4c70) + 82 at PFObjectEstimatedData.m:59
    frame #71: 0x00271d24 myApp`-[PFObject(self=0x169c3ec0, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #72: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169c3ec0, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #73: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x051b4e70, key=0x005cd5e8, obj=0x169c3ec0, stop=0x051b4de8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #74: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #75: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #76: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x169e8460, _cmd=0x31f2560c, block=0x051b4e70) + 82 at PFObjectEstimatedData.m:59
    frame #77: 0x00271d24 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #78: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169a0310, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    .......
    frame #6013: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x05230a70, key=0x005cd5e8, obj=0x169c3ec0, stop=0x052309e8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #6014: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #6015: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #6016: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x169e8460, _cmd=0x31f2560c, block=0x05230a70) + 82 at PFObjectEstimatedData.m:59
    frame #6017: 0x00271d24 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #6018: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169a0310, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #6019: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x05230c70, key=0x005cdcc8, obj=0x169a0310, stop=0x05230be8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #6020: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #6021: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #6022: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x16937f70, _cmd=0x31f2560c, block=0x05230c70) + 82 at PFObjectEstimatedData.m:59
    frame #6023: 0x00271d24 myApp`-[PFObject(self=0x169c3ec0, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #6024: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169c3ec0, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #6025: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x05230e70, key=0x005cd5e8, obj=0x169c3ec0, stop=0x05230de8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #6026: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #6027: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #6028: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x169e8460, _cmd=0x31f2560c, block=0x05230e70) + 82 at PFObjectEstimatedData.m:59
    frame #6029: 0x00271d24 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #6030: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169a0310, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #6031: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x05231070, key=0x005cdcc8, obj=0x169a0310, stop=0x05230fe8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #6032: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #6033: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #6034: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x16937f70, _cmd=0x31f2560c, block=0x05231070) + 82 at PFObjectEstimatedData.m:59
    frame #6035: 0x00271d24 myApp`-[PFObject(self=0x169c3ec0, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #6036: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169c3ec0, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #6037: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x05231270, key=0x005cd5e8, obj=0x169c3ec0, stop=0x052311e8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #6038: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #6039: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #6040: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x169e8460, _cmd=0x31f2560c, block=0x05231270) + 82 at PFObjectEstimatedData.m:59
    frame #6041: 0x00271d24 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #6042: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169a0310, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #6043: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x05231470, key=0x005cdcc8, obj=0x169a0310, stop=0x052313e8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #6044: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #6045: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #6046: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x16937f70, _cmd=0x31f2560c, block=0x05231470) + 82 at PFObjectEstimatedData.m:59
    frame #6047: 0x00271d24 myApp`-[PFObject(self=0x169c3ec0, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #6048: 0x0027ffa0 myApp`-[PFObject isDirty](self=0x169c3ec0, _cmd=0x35ab71c0) + 44 at PFObject.m:2009
    frame #6049: 0x00271e8e myApp`__29-[PFObject(.block_descriptor=0x05231670, key=0x005cd5e8, obj=0x169c3ec0, stop=0x052315e8) isDirty:]_block_invoke + 194 at PFObject.m:666
    frame #6050: 0x2f007042 CoreFoundation`__65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 98
    frame #6051: 0x2f006f66 CoreFoundation`-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 162
    frame #6052: 0x0028ba02 myApp`-[PFObjectEstimatedData enumerateKeysAndObjectsUsingBlock:](self=0x169e8460, _cmd=0x31f2560c, block=0x05231670) + 82 at PFObjectEstimatedData.m:59
    frame #6053: 0x00271d24 myApp`-[PFObject(self=0x169a0310, _cmd=0x00518b86, considerChildren='\x01') isDirty:] + 472 at PFObject.m:665
    frame #6054: 0x0027a362 myApp`__31-[PFObject(task=0x15791570) saveAsync:]_block_invoke581 + 186 at PFObject.m:1452
    frame #6055: 0x00170b76 myApp`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2(.block_descriptor=<unavailable>) + 214 at BFTask.m:334
    frame #6056: 0x0016d2ee myApp`__29+[BFExecutor defaultExecutor]_block_invoke_2(.block_descriptor=<unavailable>, block=0x05231b6c) + 602 at BFExecutor.m:45
    frame #6057: 0x0016da74 myApp`-[BFExecutor execute:](self=0x1552be20, _cmd=0x00506264, block=0x05231b6c) + 88 at BFExecutor.m:109
    frame #6058: 0x00170a78 myApp`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke(.block_descriptor=0x169a74b0) + 204 at BFTask.m:326
    frame #6059: 0x001704f0 myApp`-[BFTask runContinuations](self=0x15791570, _cmd=0x00506305) + 568 at BFTask.m:306
    frame #6060: 0x0016f84e myApp`-[BFTask trySetResult:](self=0x15791570, _cmd=0x005053ad, result=0x00000000) + 266 at BFTask.m:198
    frame #6061: 0x0016f6e2 myApp`-[BFTask setResult:](self=0x15791570, _cmd=0x33c6a3d2, result=0x00000000) + 66 at BFTask.m:185
    frame #6062: 0x00172186 myApp`-[BFTaskCompletionSource setResult:](self=0x169a18c0, _cmd=0x33c6a3d2, result=0x00000000) + 110 at BFTaskCompletionSource.m:52
    frame #6063: 0x00170db0 myApp`__55-[BFTask continueWithExecutor:block:cancellationToken:]_block_invoke_2(.block_descriptor=<unavailable>) + 784 at BFTask.m:364
    frame #6064: 0x39d63832 libdispatch.dylib`_dispatch_call_block_and_release + 10
    frame #6065: 0x39d76920 libdispatch.dylib`_dispatch_root_queue_drain + 224
    frame #6066: 0x39d76b20 libdispatch.dylib`_dispatch_worker_thread2 + 56
    frame #6067: 0x39ea5bd2 libsystem_pthread.dylib`_pthread_wqthread + 298
    frame #6068: 0x39ea5a98 libsystem_pthread.dylib`start_wqthread + 8
```

**Comment by radiovisual** [comment] 2015-09-15 17:36
I think this issue might be related to a the previously closed issue #146

**Comment by nlutsenko** [comment] 2015-09-15 17:39
Hey @radiovisual, thanks for the report!
Yup. I think this is a duplicate of #146 and was ultimately fixed with #259. 

Since it didn't get released yet, you probably aren't using that version yet. This fix is coming with v1.8.4.

I am going to close this one out, but feel free to reopen if you see the problem happening again.

**Closed by nlutsenko** 2015-09-15 17:39 UTC

**Comment by radiovisual** [comment] 2015-09-15 17:46
@nlutsenko, thanks for the quick feedback! Any news on when 1.8.4 will get released (or perhaps a temporary workaround I could employ)? My app production is nearly halted until this gets fixed. 

Thanks again for the swift reply!

**Comment by nlutsenko** [comment] 2015-09-15 19:26
@radiovisual 1.8.4 is live and available.
Crazy coincidence that we are releasing today and you asked for it :grin:

**Comment by radiovisual** [comment] 2015-09-15 23:37
Awesome! Thanks :exclamation:
