### ISSUE TITLE
Parse Query always returns Error NSCocoaErrorDomain 3840 on iOS 7

### ISSUE THREAD

**Issue by drewlarsen** [ParsePlatform/Parse-SDK-iOS-OSX#448] opened 2015-10-21 19:11 UTC
After upgrading my production app to Parse iOS SDK 1.9.0, the first Parse query the app executes returns the above error with this description:
JSON text did not start with array or object and option to allow fragments not set.

The app works fine on iOS 8.x and iOS 9.x. The error only happens on iOS 7.x. But it happens everytime on every device.

I have found a similar thread in the Parse Developers forum:
https://groups.google.com/forum/#!searchin/parse-developers/JSON$20text$20did$20not$20start$20with$20array$20or$20object$20and$20option$20to$20allow$20fragments$20not$20set/parse-developers/k2rP33XccBg/cHLs0xp3CgAJ

**Comment by wavs** [comment] 2015-10-22 10:13
Same error for me on iOS 7:
```console
Failed to run command eventually with error:
Error Domain=NSCocoaErrorDomain
Code=3840
"The operation couldn’t be completed. (Cocoa error 3840.)"
(JSON text did not start with array or object and option to allow fragments not set.)
UserInfo=0x15f1f4d0
{
    NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.
}
```

When I try this code just after install:
```Swift
let installation = PFInstallation.currentInstallation()
installation["key"] = "value"
installation.saveEventually()
```

**Comment by drewlarsen** [comment] 2015-10-22 16:14
Feedback on this? This is a major production issue!

**Comment by richardjrossiii** [comment] 2015-10-22 20:12
This definitely seems wrong. I'll see if something recently changed with our JSON parsing, and let you know what I find.

**Comment by richardjrossiii** [comment] 2015-10-22 20:25
Duplicate of #388, fixed in 1.9.1, which is releasing soon.

**Closed by richardjrossiii** 2015-10-22 20:25 UTC
Labels: duplicate

**Comment by drewlarsen** [comment] 2015-10-22 21:34
Thank you, I'm relieved to hear that.
However, I currently have a production app that now 15% of my users are completely blocked out of. This is a horrible situation for my business!
What is the release date for 1.9.1? Does soon mean tomorrow? Or next week?

**Comment by richardjrossiii** [comment] 2015-10-22 21:42
Ideally later today, barring no setbacks. No promises however.

**Comment by karthikios** [comment] 2015-10-27 12:36
Hai guys , me too face this same error for ios7
Error Domain=NSCocoaErrorDomain
Code=3840
"The operation couldn’t be completed. (Cocoa error 3840.)"
(JSON text did not start with array or object and option to allow fragments not set.)

Please help me out from this. when 1.9.1 will release?

**Comment by wavs** [comment] 2015-10-27 13:01
Already released --> https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/tree/1.9.1
Thanks for this release Parse Team.

**Comment by karthikios** [comment] 2015-10-27 13:41
Thanks wavs, updated...

**Comment by khanamir** [comment] 2016-06-17 10:45
I'm facing this issue in SDK 1.12.0. I started facing this issue by migrating code from api.parse.com to parse server hosted at Heroku. Is working fine with api.parse.com
