### ISSUE TITLE
Cannot add Parse as a dependency in a Swift Pod: "include of non-modular header"

### ISSUE THREAD

**Issue by superarts** [ParsePlatform/Parse-SDK-iOS-OSX#673] opened 2015-12-19 09:21 UTC
I'm making my Swift library that uses `Parse` to a Pod. I started from `pod lib create MyPod`, added my `.swift` files, added `s.dependency 'Parse'` in my `.podspec`, and `pod install`. Then I got a series of:

`Include non-modular header inside framework module 'Parse.Parse'.`

I searched online and found some solutions to similar problems, like setting `CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES` to `YES`, checking if the header files are public, reverting Parse version to 1.8.5, etc. but none works. I'm using `Xcode 7.2`, `Swift 2.0` and `Cocoapods 0.39.0`.

Some topics may related to this problem:

- http://stackoverflow.com/questions/33261967/cocoapods-framework-with-dependencies-include-of-non-modular-header-inside-fra/33641199#33641199
- http://stackoverflow.com/questions/24103169/swift-compiler-error-non-modular-header-inside-framework-module/24728646#24728646

**Comment by nlutsenko** [comment] 2015-12-21 19:18
Hey @superarts, the issue is actually not in Parse, but rather in how CocoaPods organizes headers when building frameworks. 

Important thing to note - importing any other framework from your own, being `sqlite3`/`Foundation` or anything else is absolutely and 100% valid and will work, as long as those frameworks have clang module. (this is what error suggests - it tries to import something that couldn't be treated as module).

According to https://github.com/CocoaPods/CocoaPods/issues/4420 the fix was already landed in `master` of CocoaPods and everything should work smooth and nice.
Could you try testing it with `master` of CocoaPods gem and let me know if it still doesn't work for you.

**Closed by nlutsenko** 2015-12-21 19:18 UTC
Labels: cocoapods
