### ISSUE TITLE
error: Error in auto-import when using lldb

### ISSUE THREAD

**Issue by arielelkin** [ParsePlatform/Parse-SDK-iOS-OSX#305] opened 2015-09-22 20:10 UTC
I get the error message below regularly in the lldb console when I `po` values.

It only goes away after I delete all the pods from the Podfile, run `pod install`, add all my pods back again to the Podfile, then run `pod install` again.

Could this be caused by the Parse SDK? 

```
error: Error in auto-import:
failed to get module 'Evino' from AST context:
/myProject/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.h:21:9: note: while building module 'FBSDKCoreKit' imported from /myProject/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.h:21:
#import <FBSDKCoreKit/FBSDKButton.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/myProject/Pods/Target Support Files/FBSDKCoreKit/FBSDKCoreKit-umbrella.h"
        ^
/myProject/Pods/Target Support Files/FBSDKCoreKit/FBSDKCoreKit-umbrella.h:6:9: note: in file included from /myProject/Pods/Target Support Files/FBSDKCoreKit/FBSDKCoreKit-umbrella.h:6:
#import "FBSDKAppLinkResolver.h"
        ^
/myProject/Pods/FBSDKCoreKit/FBSDKCoreKit/FBSDKCoreKit/FBSDKAppLinkResolver.h:26:10: error: include of non-modular header inside framework module 'FBSDKCoreKit.FBSDKAppLinkResolver'
# import <Bolts/BFAppLinkResolving.h>
         ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/myProject/Pods/Target Support Files/FBSDKLoginKit/FBSDKLoginKit-umbrella.h"
        ^
/myProject/Pods/Target Support Files/FBSDKLoginKit/FBSDKLoginKit-umbrella.h:3:9: note: in file included from /myProject/Pods/Target Support Files/FBSDKLoginKit/FBSDKLoginKit-umbrella.h:3:
#import "FBSDKLoginButton.h"
        ^
/myProject/Pods/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.h:21:9: error: could not build module 'FBSDKCoreKit'
#import <FBSDKCoreKit/FBSDKButton.h>
        ^
could not build Objective-C module 'FBSDKLoginKit'/myProject/Pods/Parse/Parse/PFAnalytics.h:12:9: note: while building module 'Bolts' imported from /myProject/Pods/Parse/Parse/PFAnalytics.h:12:
#import <Bolts/BFTask.h>
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/myProject/Pods/Target Support Files/Bolts/Bolts-umbrella.h"
        ^
A fatal parse error has occurred.  LLDB may become unstable; please restart your debug session as soon as possible.
```

**Comment by richardjrossiii** [comment] 2015-09-22 20:13
Seems like an LLDB bug to me... I would strongly suggest clearing Xcode's DerivedData directory and see if that helps at all. Could be an issue with Xcode's internal module cache. 

I don't think this is related to the Parse SDK, and I would see if you can create a smaller reproduction project and send it along to Apple and/or the LLVM team.

**Comment by richardjrossiii** [comment] 2015-09-28 20:43
Closing this issue due to no more activity. Feel free to comment on this if you need any more help with this issue.

**Closed by richardjrossiii** 2015-09-28 20:43 UTC
Labels: question
