### ISSUE TITLE
Local Datastore losing information for PFObjects when app is killed

### ISSUE THREAD

**Issue by barryllium** [ParsePlatform/Parse-SDK-iOS-OSX#131] opened 2015-08-28 20:09 UTC
In an app I'm working on, I have a class named Group.  It subclasses PFObject, and has two variables: owner (which is a reference to the current user) and name, which is a String. I have Two scenarios, same code base - 

Scenario 1:
1. Log into app
2. Put phone in airplane mode
3. Create 4 groups with the following names: a, aa, aaa, aaaa
4. Kill the app
5. Open the app
6. Go to groups page - only one group is listed, with name aaaa
7. Take phone out of airplane mode
8. Wait 10-15 seconds (long enough for phone to connect and have enough time to save to the server)
9. Refresh group list, still only see group aaaa

Scenario 2:
1. Log into app
2. Put phone in airplane mode
3. Create 4 groups with the following names: b, bb, bbb, bbbb
4. Take phone out of airplane mode (we have not killed the app at this point, but it’s important to note that backgrounding/foregrounding the app has no effect or issue)
5. Wait 10-15 seconds (long enough for phone to connect and have enough time to save to the server
6. Refresh group list, see all four groups still exist

When I look online at our Group table, I see eight rows.  Five of these rows have all the correct info - the rows for aaaa, b, bb, bbb, bbbb.  The other 3 rows (assumedly for the groups I named a, aa, and aaa) have info for objectId, createdAt, updatedAt, and ACL - but name and owner are both listed as undefined.  This leads me to believe that the local datastore is losing that info when the app is killed.  Here is my code that is giving the issue:

Group class:
```
class Group: PFObject, PFSubclassing {
    
    static func parseClassName() -> String {
        return "Group"
    }
    
    @NSManaged var owner: TrustTreeUser // This class subclasses PFUser
    @NSManaged var name: String
    
    func saveGroup() {
        if IJReachability.isConnectedToNetwork() {
            self.saveInBackground()
        } else {
            self.saveEventually()
        }
    }
}
```

Creating and saving the Group instance:
```
var newGroup = Group()
newGroup.name = groupName // this is a string passed in from a UIAlertController
newGroup.owner = TrustTreeUser.currentUser()!
newGroup.saveGroup()
```

This is is happening running iOS 8.4.1, Xcode 6.4, and has been experienced in Parse versions 1.8.0-1.8.2

**Comment by nlutsenko** [comment] 2015-08-28 20:47
Hey @barryllium, thanks for the report.
Any chance you can attach a console log that you are seeing to this issue?
Just want to confirm that save succeeds here. If not - in debug mode  you will see the errors being logged to the console.

Also, a repro project with full or partial schema that reproduces the problem would be very helpful.

**Comment by barryllium** [comment] 2015-08-31 13:33
The Console shows no errors at any point during the process.  I've set up a test repo set up here: https://github.com/barryllium/ParseTest

You'll need to run a pod update after pulling.

**Comment by bluecollar** [comment] 2015-09-05 16:05
Any updates on this? is a show-stopper on our side. Much thanks

**Comment by gavinbunney** [comment] 2015-09-11 02:20
:+1: Seeing this issue as well - happens a lot when you have a device connected and relaunch (since it kills the app)

**Comment by bluecollar** [comment] 2015-09-11 16:17
@nlutsenko - have you pulled @barryllium 's test repo? have you been able to replicate? how far along is this?

Much thanks

**Comment by nlutsenko** [comment] 2015-09-11 16:21
Got tangled with a lot of things, so not yet.
If you have more info on this guys - it would be a tremendous help.

**Comment by bluecollar** [comment] 2015-09-11 16:24
@nlutsenko - Which step are you on? @barryllium has the mastery of the issue, but he has posted a test repo for you here - "

https://github.com/barryllium/ParseTest

You'll need to run a pod update after pulling. "

Can you look into pulling this repo today and trying to reproduce? Or if you have, let us know specifically what additional info you need? We are here and ready to get you whatever you need. It's kind of urgent on our side.. much much appreciated.

**Comment by richardjrossiii** [comment] 2015-09-11 16:26
As @nlutsenko is traveling right now, I'll take a look at it later today.

**Comment by nlutsenko** [comment] 2015-09-11 16:26
@richardjrossiii, thank you, sir!

**Comment by nlutsenko** [comment] 2015-09-11 16:27
Hmm... not sure if assignment are correct...

**Comment by richardjrossiii** [comment] 2015-09-11 16:27
The drop down is terrible from mobile. My bad.

**Comment by bluecollar** [comment] 2015-09-11 16:46
@richardjrossiii (and @nlutsenko ) THANK YOU very much, we've been eagerly waiting for this to get looked at. It's foreseeably our last showstopping bug before we can go to production. Let me know if you need anything at all

**Comment by richardjrossiii** [comment] 2015-09-11 19:11
I have confirmed that this is indeed an issue in the SDK. I have been unable so far to track down the precise location of the issue, but the good news is that the objects are still in LDS, just all of their fields have been stripped for some reason. I'll keep you up to date on what else I find, as well as any potential workaround that I may encounter.

**Comment by richardjrossiii** [comment] 2015-09-11 21:48
I have found the source of this issue and will be creating a PR shortly. Thank you for the repro case, this was certainly a nasty one to track down!

**Comment by barryllium** [comment] 2015-09-11 21:51
Awesome - so judging by the log we should see this in 1.8.4?

**Comment by richardjrossiii** [comment] 2015-09-11 21:55
@barryllium Yep, or once the PR has landed, you can test it with master, by putting this in your pod spec:

    pod 'Parse', :git => "https://github.com/parseplatform/parse-sdk-iOS-OSX.git"

**Closed** 2015-09-15 02:44 UTC
Labels: bug
