### ISSUE TITLE
Problem after updating to 1.8.2

### ISSUE THREAD

**Issue by chanaschloss** [ParsePlatform/Parse-SDK-iOS-OSX#178] opened 2015-09-06 15:28 UTC
after i updeted to version 1.8.2 ,
i get this error:
(Code: 0, Version: 1.8.2)
every time i try to login a user via email

**Comment by nlutsenko** [comment] 2015-09-06 18:27
Hey @chanaschloss, this sounds sad and unexpected.
I've tested this against current latest master and it works beautifully.
Any chance you can attach a repro project or at least name of the app + username + password?
Looks like without this we can't reproduce the problem, and this would help us fix the problem faster.

**Comment by chanaschloss** [comment] 2015-09-07 10:26
hey Nikita,
thank you.
the name of the app - Fruitful	
you can try - username - foo@foo.com <mailto:foo@foo.com> password - zzzzzz
I hope this helps and you can help me to solve the problem as fast as possible.

thank you.
כתיבה וחתימה טובה
‫חנה שלאס‬‎
054-8478262
chnschloss@gmail.com

**Comment by nlutsenko** [comment] 2015-09-07 16:38
Perfect, thank you, testing now...

**Comment by nlutsenko** [comment] 2015-09-07 16:51
As I originally thought and just confirmed against your app - this issue was already fixed in latest master with #147. 

The next release `1.8.3` is coming very soon, but until then - feel free to use `master` branch from say Cocoapods by using this line in your Podfile:
`pod 'Parse', :git => 'https://github.com/ParsePlatform/Parse-SDK-iOS-OSX'`

The other option - clone the repository locally and build the release for your self (the instructions are in the README, but it's basically few commands).

Please note, that using master is usually *not safe*, since sometimes there could be breaking changes/missing functionality that gets resolved before every release (not yet happened, but just warning about potential of this happening).

**Closed by nlutsenko** 2015-09-07 16:51 UTC
Labels: needs more info
