### ISSUE TITLE
Parse Local DB issue on iOS app Launch

### ISSUE THREAD

**Issue by narendra117** [ParsePlatform/Parse-SDK-iOS-OSX#505] opened 2015-11-03 11:58 UTC
I am using parse local data store and querying data from local store. It works well when app install and when i came back to app and try to get data from local datastore it takes very long time for first time of each launch.
This is the call for query local DB,

    PFQuery *userDetailsQuery=[PFQuery queryWithClassName:@"_User"];
    [userDetailsQuery whereKey:@"objectId" containedIn:familyArray];
    [userDetailsQuery fromLocalDatastore];
    [userDetailsQuery fromPinWithName:USERS_PIN_NAME ];
    [userDetailsQuery findObjectsInBackgroundWithBlock:^(NSArray *objects, NSError *error) {
        //Long Time to get response.
    }];

I am using latest Parse SDK from cocoapods.  I am performing very huge local db operations when launch app.
Fix this issue and if their is already way to solve this then please give the solution.

**Comment by oskarl** [comment] 2015-11-03 13:11
Yes, I had this problem too. I ended up just using CoreData for the local storage part of my app because Parse's local datastore is way too slow.

**Comment by richardjrossiii** [comment] 2015-11-03 17:57
Duplicate of #32.

**Closed by richardjrossiii** 2015-11-03 17:57 UTC
Labels: duplicate
