### ISSUE TITLE
Local Database Latency Issues

### ISSUE THREAD

**Issue by awareads** [ParsePlatform/Parse-SDK-iOS-OSX#149] opened 2015-09-01 14:57 UTC
Accessing larger amounts of data within the database with reads and writes can take in upwards of 2-3 minutes. The read and writes into the single JSON file is causing the main issue that we are experiencing with our implementation on a mobile iOS application. Is it possible that this can be converted to an SQL database? The current load times could be drastically reduced to seconds.

**Comment by richardjrossiii** [comment] 2015-09-01 20:45
Duplicate of #32

**Closed by richardjrossiii** 2015-09-01 20:45 UTC
