### ISSUE TITLE
Crash when receiving a remote notification with the application active

### ISSUE THREAD

**Issue by maxbryan** [ParsePlatform/Parse-SDK-iOS-OSX#278] opened 2015-09-17 18:13 UTC
After updating to the newest SDK I ran across this crash that happens every time I get a notification while the application is active. As soon as I press OK on the notification this happens. Also, we handle the notification by presenting a new view controller to the user based off the notification. It looks like PFAlertView is trying to present itself at the same time or something...
<img width="1868" alt="screen shot 2015-09-17 at 1 07 25 pm" src="https://cloud.githubusercontent.com/assets/3952680/9941896/d491f8ec-5d3d-11e5-91cb-f9288ce5b30a.png">

**Comment by richardjrossiii** [comment] 2015-09-17 18:16
Duplicate of #269, fixed in #272. Will be fixed in 1.8.5, which should be released later today.

**Closed by richardjrossiii** 2015-09-17 18:16 UTC
