### ISSUE TITLE
Error "-[PFObjectState length]: unrecognized selector sent to instance"

### ISSUE THREAD

**Issue by apersaud** [ParsePlatform/Parse-SDK-iOS-OSX#39] opened 2015-08-18 04:37 UTC
Running with the new Parse SDK 1.8.0, with a table called 'LaunchCity' that contains a `state` column, an unrecognized selector exception is thrown and the actual column value is never retrieved.

![screen shot 2015-08-17 at 9 36 48 pm](https://cloud.githubusercontent.com/assets/127068/9322468/1aa657d4-4528-11e5-9c41-5c610655bec6.png)

Table Schema:
![screen shot 2015-08-17 at 9 34 40 pm](https://cloud.githubusercontent.com/assets/127068/9322450/eaa17f6e-4527-11e5-84a2-4cbbb42c413f.png)

Data Seed:
https://dl.dropboxusercontent.com/u/119336/LaunchCity.json

Sample Project:
https://dl.dropboxusercontent.com/u/119336/ParseSampleUnRecognizedSelector.zip

**Comment by nlutsenko** [comment] 2015-08-18 04:40
Hey @apersaud, this is a duplicate of already closed issue #33 that was fixed today and the fix is already present in the master.
If you want to use it right now - you can simply change your Podfile to reference master by adding:
`pod 'Parse', :git => 'https://github.com/ParsePlatform/Parse-SDK-iOS-OSX.git'`

**Closed by nlutsenko** 2015-08-18 04:40 UTC

**Comment by apersaud** [comment] 2015-08-18 04:41
Thanks!
