### ISSUE TITLE
Issue with Localizable.string file

### ISSUE THREAD

**Issue by tourou** [ParsePlatform/Parse-SDK-iOS-OSX#58] opened 2015-08-19 18:52 UTC
Hi guys, when will you be able to make a new release for this pod with the new name for you localisable strings file name ? It actually messes up with my whole project and I would be pleased to have this fixed before releasing our next version of our application.

**Comment by nlutsenko** [comment] 2015-08-19 18:54
You can always use a pod from master with the fix included. Instructions are in #16 (which this one is a duplicate of).

**Comment by nlutsenko** [comment] 2015-08-19 18:58
And, as a crazy coincidence - the next release is live. (1.8.1)

**Closed by nlutsenko** 2015-08-19 18:58 UTC
Labels: duplicate
