### ISSUE TITLE
Parse 1.8.4 + Bolts 1.2.2 + XCode 7.1Beta + iOS 8.4 = Error

### ISSUE THREAD

**Issue by anclefeudor** [ParsePlatform/Parse-SDK-iOS-OSX#270] opened 2015-09-16 13:52 UTC
Parse 1.8.3 works well

Parse 1.8.4 throws lots of errors with compile like:

```
/Users/ancle/Documents/Ios/Webka/Webka/Pods/Headers/Public/Parse/PFAnalytics.h:44:4: Type arguments cannot be applied to non-parameterized class 'BFTask'

/Users/ancle/Documents/Ios/Webka/Webka/Pods/Headers/Public/Parse/PFObject.h:319:4: Type arguments cannot be applied to non-parameterized class 'BFTask'
```

What i need to do? Use 1.8.4 and test only with iOS9?
It will work on iOS8 devices after submit to AppStore?

**Comment by nlutsenko** [comment] 2015-09-16 18:35
Hey @anclefeudor thanks for the report!
I wonder if Xcode 7.1 changed something in generic type signatures.
Any chance you can test with Xcode 7 (it is available through Mac App Store now).

**Comment by anclefeudor** [comment] 2015-09-16 20:43
Xcode 7 works well. 
Will watch for betas.

**Comment by anclefeudor** [comment] 2015-09-16 20:55
Oops, wait. There is reverse situation. Xcode 7 + Parse 1.8.4 dosen't works on iOS 9. I got same errors.

**Comment by richardjrossiii** [comment] 2015-09-16 21:02
Quick thought. Are you sure you have the latest Bolts version? (Check BFTask.h) for cases `BF_GENERIC`.

**Comment by anclefeudor** [comment] 2015-09-16 21:03
Pod said "Using Bolts (1.2.2)"

**Comment by nlutsenko** [comment] 2015-09-17 00:10
The only thing I would suggest is to try cleaning your Derived Data, since that one could be stale.
As well as maybe removing `Pods` directory and reinstalling every single pod by running `pod install`.
It might be the case where the compiler is using the cached version of the headers instead of the latest one.

**Comment by dtaitz** [comment] 2015-09-17 22:49
I am also having this issue

**Comment by nlutsenko** [comment] 2015-09-17 22:50
The issue should only appear if you are using old version of Bolts (pre 1.2.2), since that one doesn't have generic types in headers. It would be amazing to have a repro project for this, since neither I nor @richardjrossiii can reproduce this.

**Comment by dtaitz** [comment] 2015-09-17 22:57
I am using Xcode 7.0, Parse 1.8.4, and Bolts 1.2.2. The weird part about this is that I am able to build my project on the simulator but unable to do so when I try to build it in my iPhone (an iPhone 5s). I originally had iOS 8.4 installed when I first ran into the problem and then I updated to iOS 9.0 and still ran into the same issue. I am going to try to update to the Xcode 7.1 beta and see if it was resolved

**Comment by nlutsenko** [comment] 2015-09-17 22:58
@dtaitz I suppose you tried cleaning `Pods` and Xcode `DerivedData`, right?

**Comment by dtaitz** [comment] 2015-09-17 23:01
Yes I have. This started to occur when I installed Xcode 7.0 this morning.

**Comment by nlutsenko** [comment] 2015-09-17 23:02
Any chance you can attach a small project (it can be anything) that reproduce the problem for you?

**Comment by dtaitz** [comment] 2015-09-17 23:05
@nlutsenko  I will add you as a collaborator on my project. Hold on.

**Comment by nlutsenko** [comment] 2015-09-17 23:41
@dtaitz Just checked out the project, ran `pod install`, opened the scheme and built for both Simulator and Device.
Proof attached: :D
![screen shot 2015-09-17 at 4 40 52 pm](https://cloud.githubusercontent.com/assets/606991/9948781/e7346aa8-5d5a-11e5-811f-d080a5759870.png)

**Comment by nlutsenko** [comment] 2015-09-17 23:41
Suggestion - try running `git clean -xffd` inside your local git checkout for the project.
This will remove everything that is ignored by git, so you have a clean checkout.

**Comment by dtaitz** [comment] 2015-09-17 23:43
Thanks @nlutsenko ! I appreciate you spending the time helping me resolve this issue. I will run that command and see if it solves the issue!

**Comment by dtaitz** [comment] 2015-09-18 00:05
It worked! Thanks again!

**Comment by nlutsenko** [comment] 2015-09-18 00:06
Woohoo!
Let me know if there is anything else I can help you with...

**Comment by nlutsenko** [comment] 2015-09-18 00:07
@anclefeudor Try using the same solution aka run `git clean -xffd` inside your repo.
It will delete every ignored file in your repository, so if you have any artifacts from old version of Bolts.framework - it will simply remove those.

**Comment by anclefeudor** [comment] 2015-09-18 09:29
Ok, i will try

**Comment by A1iAshoor** [comment] 2015-09-25 01:03
Tried the above, didn't work..

1# by commenting those and run the 'pod install' command:
```
#pod 'FBSDKCoreKit'
#pod 'FBSDKLoginKit'
#pod 'Parse'
```

2# uncomment them and redo 'pod install' did the trick, as now Bolts 1.3.0 installed and used.

**Comment by nlutsenko** [comment] 2015-09-25 01:15
Perfect. That meant that probably Cocoapods were caching the old Bolts somewhere and deleting them/adding them helped.
I am going to close this issue, if someone still runs into this - please let us know in #297

**Closed by nlutsenko** 2015-09-25 01:15 UTC
Labels: needs investigation
