### ISSUE TITLE
[PFObject pin] takes longer time with more objects saved in LocalDataStore

### ISSUE THREAD

**Issue by noughts** [ParsePlatform/Parse-SDK-iOS-OSX#135] opened 2015-08-29 01:21 UTC
It seems that [PFObject pin] takes longer time with more objects saved in LocalDataStore
When LocalDataStore is empty, it takes only 50ms to pin 10 ParseObjects.
When there are 500 objects in LocalDataStore, it takes 750ms to pin.
When there are 1,000 objects in LocalDataStore, it takes 1480ms to pin.

I've attached a simple repro project file using Starter Project.
https://dl.dropboxusercontent.com/u/309225/LocalDataStorePerformance.zip
By running it, you can see that pin is repeated, and its process time gets longer and longer.

Is there any way to make this faster?
Thanks for your advice.

Environment:
Parse SDK 1.8.1
iPhone6

**Comment by richardjrossiii** [comment] 2015-08-29 01:22
Duplicate of #32.

**Closed by richardjrossiii** 2015-08-29 01:22 UTC

**Comment by noughts** [comment] 2015-08-29 03:33
Oh I've never noticed LDS means LocalDataStore.

**Comment by PSIPhone** [comment] 2015-09-24 13:15
i am getting same issue and i am totally frustrated after choosing parse. I want to go for paid plan but this issue is the hurdle to my project. Did you get any solution?

**Comment by richardjrossiii** [comment] 2015-09-24 20:19
We are tracking this on #32, and currently, we have a solution for one aspect of LDS performance for release in 1.9.0.

**Comment by PSIPhone** [comment] 2015-09-28 05:25
When 1.9.0 will be released, my project is stuck for that?

I would recommend your support on this.

**Comment by nlutsenko** [comment] 2015-09-28 06:27
It's coming soon, no specific time set, but you can get a rough estimate from looking at the periods of previous releases.

**Comment by PSIPhone** [comment] 2015-09-28 09:32
Latest iOS sdk is 1.8.5 and upcoming will be 1.9.0 or 1.8.6?

And 1.9.0 will solve this issue of slow pin?

**Comment by nlutsenko** [comment] 2015-09-28 09:35
@PSIPhone, 1.9.0 will improve the performance with pinning and querying objects in Local Datastore.
Solve this issue - up to extent. As I and Richard previously mentioned - we are working on improving overall experience and performance with Local Datastore and tracking progress in #32.

Next version is going to be 1.9.0, according to the milestones in this repository.

**Comment by PSIPhone** [comment] 2015-09-28 09:46
Ok waiting and hope this will fix if i have thousands of rows in a table.
