### ISSUE TITLE
PFSubclassing might  not be working properly with boolean values

### ISSUE THREAD

**Issue by dev-mush** [ParsePlatform/Parse-SDK-iOS-OSX#112] opened 2015-08-26 09:37 UTC
On a subclass I have of PFUser I have a boolean property.
Since my last update anyway I keep on receiving this error:

`[Error]: invalid type for key myPropertyName, expected boolean, but got number (Code: 111, Version: 1.8.0) `

when calling the selector `signUpInBackgroundWithBlock:` , I assume there might be some problem in converting the dynamic property to an nsnumber, I've tried to dig into your code to find out but had not much time to understand where the problem might be, even because I can't diff with the previous version of it.

**Comment by richardjrossiii** [comment] 2015-08-26 09:51
Dupe of #13, fixed in 1.8.1.

**Closed by richardjrossiii** 2015-08-26 09:51 UTC
