### ISSUE TITLE
Crash reporting not working

### ISSUE THREAD

**Issue by osklar0328** [ParsePlatform/Parse-SDK-iOS-OSX#551] opened 2015-11-12 13:21 UTC
I'm trying to get the crash reporting to work in my app. I can't get any crash reports in my dashboard. I'm using swift 2.0, Xcode 7.1.1 and I've installed Parse v1.9.1 using cocoapods. The report navigator shows no errors and everything is successfully run:

    Uploading iOS symbol files...
    
    Uploaded symbol files.
    
    Touch MyParseApp.app
    
    ProcessProductPackaging 
    
    Copying Swift standard libraries into MyParseApp.app
    
    Process product packaging
    
    Sign MyParseApp.app
    
    Validate MyParseApp.app
    
    Build succeeded

I've used the Run Script Phase suggested in the quick step guide:

    export PATH=/usr/local/bin:$PATH cd /Users/osl/Projects/MyParseApp/ParseCloudCode parse symbols -p "${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}"

My cloud code directory "ParseCloudCode" in my Xcode project directory contains these files:

    .parse.local
    {
           "applications": {
           "MyParseApp": {
           "applicationId": "******************************"
    },
    "_default": {
      "link": "MyParseApp"
    }

    .parse.project
    {
          "project_type": 1,
          "parse": {
          "jssdk": "latest"
     },
      "email": "*****@*****.com"
    }

and I created i by using the `parse new` command in my Xcode project directory. I then choose my existing Parse application that I wanted to report the crashes to.

Is there something I'm missing when setting up my cloud code?

**Comment by nlutsenko** [comment] 2015-11-12 18:06
Duplicate of #444.
We were able to bisect this to be purely a backend issue.
Could you file an issue on https://parse.com/help , since we are still using FB Bug Tool to track backend issues.

**Closed by nlutsenko** 2015-11-12 18:06 UTC
