### ISSUE TITLE
"Can't upload a file that doesn't exist locally." when saving PFObject with no PFFile

### ISSUE THREAD

**Issue by GabrielMSharp** [ParsePlatform/Parse-SDK-iOS-OSX#766] opened 2016-01-16 13:49 UTC
Saving ANY PFObject currently gives Error 151, irrespective of whether that PFObject has a PFFile, unsaved or not. I think this is generally linked to the Localdatastore and is a development on the issue I posted here: https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/issues/763

**Comment by nlutsenko** [comment] 2016-01-19 02:01
This sounds very strange, as error 151 is thrown only in 2 places, either when you are trying to download a file that was never saved to the server or when a file download was cancelled on saving an object.
Not sure, but doesn't look like you are hitting any of these. Any chance you can attach a code sample/project that can reproduce the issue?

**Comment by JasonPanAD** [comment] 2016-02-01 05:36
I'm getting the same issue:

Error saving Error Domain=Parse Code=151 "Can't upload a file that doesn't exist locally." UserInfo={error=Can't upload a file that doesn't exist locally., NSLocalizedDescription=Can't upload a file that doesn't exist locally., code=151}

**Comment by jacobkneal** [comment] 2016-02-01 16:15
I'm getting the same issue after migrating to Parse Server (Heroku/MongoLab) as well.

**Comment by danieleng** [comment] 2016-02-02 18:39
Also having the same issue after migration to Parse Server. Was working just fine before.

**Comment by juancruzmdq** [comment] 2016-02-03 13:29
I have the same issue after migrating to Parse Server (Heroku with MongoLab addOn), this happen when I try to save the user profile with:
"[[PFUser currentUser] saveInBackgroundWithBlock:...]"

When I try to save another object I have this error:
"[Error]: Object not found. (Code: 101, Version: 1.12.0)"

All ACL perms seems to be ok, and was working fine before migration

**Comment by toboklee** [comment] 2016-02-03 17:12
I ran into this problem after migration....

To fix the problem, find all the columns that use PFFile.
Then, in the database retrieve the files manually and need to upload again...

For me, it was happening due to profile images, so I saved the images locally; then, used

    UIImage *tmp = [UIImage imageNamed:@"Image you saved"];
    PFFile *file = [PFFile fileWithData:UIImageJPEGRepresentation(tmp, 1.0f)];
    
    [[PFUser currentUser] setObject:file forKey:@"key"];
    [[PFUser currentUser] saveInBackground];

**Comment by mamoun1101** [comment] 2016-02-04 16:37
@toboklee Can you elaborate more about how did you solve this problem, what do you mean by retrieve the files in manually in the database ( I have the same issue)

**Comment by otto1020** [comment] 2016-02-06 17:24
@toboklee 
Thanks for sharing how to fix this issue.

But I can't fix this issue with your method.

Here is my code.
NSData *imageData = UIImageJPEGRepresentation([UIImage imageNamed:@"add_photo"], 0.8f);
    PFFile *userPhoto = [PFFile fileWithName:@"avatar.png" data:imageData];
    [currentUser setObject:userPhoto forKey:@"photo"];
    [currentUser saveInBackground];

Looking for hearing from you.

Thanks

**Comment by CommunityLabsLoca** [comment] 2016-02-07 05:00
I'm getting this issue when I save an object that has a pointer to a PFUser. If I save everything but the pointer, the object saves. But once I add [LKFActivity setObject:[PFUser currentUser] forKey:@"activityUser" ] then I get the error message: Can't upload a file that doesn't exist locally. (Code: 151, Version: 1.12.0). Any thoughts?

**Comment by otto1020** [comment] 2016-02-09 03:41
Actually, my development is on migration parse server.(Heroku)

Here is my original code.
`[currentUser setValue:@"YES" forKey:PF_USER_ONLINE_STATUS];
    [currentUser saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
        if (!error) {
            NSLog(@"Success!");
        } else
            [ProgressHUD showError:error.localizedDescription Interaction:YES];
    }];`
After migration, this code does not work. That's why I got error message "Can't upload a file that doesn't exist locally.".

Before migration, this code works very well.

I don't know why this issue occurs.

Also I am working on XCode 7.2/iOS 9.2

**Comment by otto1020** [comment] 2016-02-09 09:45
I am working on migration parse.

So I could migrate Parse DB to MongoDB using MongoLab.
Also I could change parse-server-example;

add cloud code(for mandrill-api and twilio) in main.js.(this works very well)
deploy to Heroku.
However, I have some issues here.

On iOS development side, when the user logs in, app don't progress any PFObject.

if I am going to change user's profile(string, boolean, image and so on), I get error message
[Error]: Can't upload a file that doesn't exist locally. (Code: 151, Version: 1.12.0)

If I am going to download the user's photo, I get error message.
[Error]: Can't download a file that doesn't exist on the server or locally. (Code: 151, Version: 1.12.0)

Also I found a strange issue.
After migration, I created a new account on my app.(without user's photo)
First, it seems it works very well

But If I upload user's photo, connection error occurs.

What's matter?

I hope you can help me.

Thanks

**Comment by toboklee** [comment] 2016-02-09 15:50
Hmm... 
Double check if the file is in fs.file in MongoDB.
Also, you have to check with fs.chunks to make sure that the binary data is available.

**Comment by otto1020** [comment] 2016-02-09 16:20
@toboklee 
Thanks a lot

I don't know what are fs.file and fs.chunks.

Here are the screenshots of them

![mongodb](https://cloud.githubusercontent.com/assets/16714648/12922336/ad1ced88-cf59-11e5-9ebe-5c5072da6e2b.png)

![fs chunks](https://cloud.githubusercontent.com/assets/16714648/12922357/c72b87e8-cf59-11e5-8501-2ef052626a81.png)

![fs file](https://cloud.githubusercontent.com/assets/16714648/12922363/ce47c8ac-cf59-11e5-9d14-aeaa0f26b16f.png)

Please explain in more detail.

**Comment by tdunham02** [comment] 2016-02-10 16:33
My solution:

Save the PFFile as usual, when saving it to Heroku (MongoLabs), save the file's URL to an NSString field. From there, load the image from the URL with AFNetworking...

```
PFFile *image = [PFFile fileWithData:imageData];
[image saveInBackgroundWithBlock:^(BOOL succeeded, NSError *error) {
    if (!error) {         
        //Set user data
        user[@"picture"] = image;
        user[@"pictureLink"] = image.url;
        [user saveInBackground];
    }
}];
```

Load:

```
if (user[@"pictureLink"]) {
    [imageView setImageWithURL:[NSURL URLWithString:user[@"pictureLink"]] placeholderImage:nil];
}
```


Not sure if this is the best way, but it works!

**Comment by juancruzmdq** [comment] 2016-02-11 19:11
Any one tried turning failIndexKeyTooLong to False? I can't do it, because I have a freeplan in mongolab
db.runCommand( { setParameter: 1, failIndexKeyTooLong: false } )

**Comment by toboklee** [comment] 2016-02-12 22:06
@otto1020 
can you try it again with parse-server 2.0.8?

**Comment by michaelbina** [comment] 2016-02-18 08:39
I just upgraded to parse-server 2.0.8 and am still seeing this issue.  Has anyone found a good solution to this yet?

**Comment by jacobkneal** [comment] 2016-02-18 13:48
Nope

**Comment by michaelbina** [comment] 2016-02-19 06:13
If it helps anyone that is still looking into this issue, here is a screenshot of the call stack and error details when I'm getting this:

<img width="1276" alt="screen shot 2016-02-18 at 10 09 26 pm" src="https://cloud.githubusercontent.com/assets/528845/13167923/b12295ec-d68c-11e5-96ec-1c66d5c1fdd3.png">

This happens consistently when I'm trying to upload to parse-server hosted on Heroku with a MongoLabs database. I've seen it when creating a new object in a class and uploading an image to one of the fields and also seen it when creating an object that has an image field that I'm not setting on creation. This seems to be a widespread issue when calling saveInBackgroundWithBlock on new objects.

**Comment by mbhuta** [comment] 2016-02-19 12:19
This issue occurs even with the 'save()' method, not just the saveInBackground() methods...so annoying. >:( No idea what to do

**Comment by dcdspace** [comment] 2016-02-22 04:37
I have this problem too, and now I can't update any user info because of it. Everything worked fine before moving over to the server.

**Comment by danieleng** [comment] 2016-02-22 19:26
I still have this issue. Parse Server on Heroku/Mongolab.
If a user object has a file stored in it (in my case image files), it´s not possible to save the user object and I get this error message: 
"Error Domain=Parse Code=151 \"Can\'t upload a file that doesn\'t exist locally.".

It is possible to fix the issue temporarily by deleting the image files manually through the database. Then I can also add new files through my apps interface and everything works like a charm again.
Until I log out of the application. If I do that and try to log in again, the error reoccurs with the same error message. 

Any ideas?

**Comment by michaelbina** [comment] 2016-02-23 01:37
Glad to know I'm not the only one having this issue.  It's stopped me from moving forward with my transition onto Heroku/Mongolab for the time being.  I even went through the process of deleting all of the data in the classes which were getting this issue and that seemed to solve it for a bit until I later uploaded files again to those classes and it would come back and not go away.  

It seems this is an issue with classes that have at least one option PFFile column in them.  The code may be expecting a file but not getting one.

I've identified that the only place this error can be called is in PFFileController.m at line 216:

`
- (BFTask<PFFileState *> *)uploadFileAsyncWithState:(PFFileState *)fileState
                                     sourceFilePath:(NSString *)sourceFilePath
                                       sessionToken:(NSString *)sessionToken
                                  cancellationToken:(BFCancellationToken *)cancellationToken
                                      progressBlock:(PFProgressBlock)progressBlock {
    if (cancellationToken.cancellationRequested) {
        return [BFTask cancelledTask];
    }
    if (!sourceFilePath) {
        NSError *error = [PFErrorUtilities errorWithCode:kPFErrorUnsavedFile
                                                 message:@"Can't upload a file that doesn't exist locally."];
        return [BFTask taskWithError:error];
    }
`

I believe that should be called when a value for a PFFile is present, but it is still being called for me when no file is uploaded for a field so it's getting to this point erroneously.  

@nlutsenko - I know this isn't a set of reproducible steps (I'll work on that) but do you have any ideas here?  It seems this a problem for multiple people now.

**Comment by dcdspace** [comment] 2016-02-23 02:04
I think Parse is coming out with a [file migrator tool](https://github.com/ParsePlatform/parse-server/issues/8) to move files from their S3 bucket to your own, so I'm hoping this is a GridStore problem.  This also is stopping me from continuing development on my Parse Server, as the app cannot function until this is fixed. 

I've found that if you upload a new file on Parse Server to Gridstore, it will only be visible to other clients checking from the server, which isn't great for legacy users. Longterm plan is to store everything in S3, but this needs to get fixed first for that to work.

**Comment by michaelbina** [comment] 2016-02-23 02:06
I set up my parse server to store files on my own S3 bucket instead of gridstore and am still having this issue so I'm not sure that is going to fix it.

**Comment by dcdspace** [comment] 2016-02-23 02:10
Thanks for letting me know, I haven't used the S3 adapter yet but hoped it would fix it, guess not. Not sure how to fix this now...

**Comment by michaelbina** [comment] 2016-02-23 07:45
I'm now seeing this happening on my device only and not in simulator with the same code and similar input.  Not sure what the main variables are that might make a difference there.  Any ideas?

**Comment by nlutsenko** [comment] 2016-02-24 23:20
Hey everyone, we found few places where this was happening in Parse-Server.
The fixes are in place right now for few things (like /users/login) and one more fix is incoming in https://github.com/ParsePlatform/parse-server/pull/637

All of this means that the fix is going to come out very soon (likely this week) and after you upgrade your Parse Server - it will be ultimately fixed.

**Comment by jacobkneal** [comment] 2016-02-24 23:26
Awesome!

**Comment by dcdspace** [comment] 2016-02-25 00:11
Thank you!

**Comment by nlutsenko** [comment] 2016-02-25 01:07
Hey guys,

Parse-Server 2.1.3 is out, and includes fixes for this issue.
Please upgrade your server, test it and comment here if this still reproduces for you.
Be aware, that if you had a cached File somewhere on the client - you might want to refresh that cache, since the URLs might be missing in it.

**Comment by dcdspace** [comment] 2016-02-25 01:26
@nlutsenko It works thank you so much! A small problem though is that when uploading new files to Mongolab's Gridstore, older clients not connected to the new Parse Server cannot access them. They are displayed as `.bin` in the Parse Dashboard and they say "Access Denied" when clicking on them in the dashboard.

I haven't tried the S3 adapter yet but am planning on switching to it, would that solve the problem? Thanks.

**Comment by CommunityLabsLoca** [comment] 2016-02-25 04:59
I know this is a really dumb question, but could you explain how to update to Parse Server 2.1.3 or direct me to an explanation? I have MongoLabs and Heroku set up, but I don't know how updating works.
Thank you!

Also a tutorial on the S3 adapter would be really helpful if one exists!

**Comment by michaelbina** [comment] 2016-02-25 12:34
run:

'npm update' 

from your root directory to update your libraries.  Make sure you don't have a hardcoded version set up in package.json.

Here is the manual for S3 adapter: https://github.com/ParsePlatform/parse-server/wiki/Storing-Files-in-AWS-S3

**Closed** 2016-03-03 07:41 UTC
Labels: needs more info

**Comment by ryderjack** [comment] 2016-03-07 22:57
@nlutsenko I've updated Parse Server to 2.1.4 but still seeing this error when saving a PFFile
`Can't upload a file that doesn't exist locally. (Code: 151, Version: 1.12.0)`

Any suggestions?

**Comment by jacobkneal** [comment] 2016-03-07 23:11
@ryderjack initially updating didn't work for me either until I created a new project with the server from scratch (instead of just updating via npm).

**Comment by juancruzmdq** [comment] 2016-03-07 23:47
I think that you have to update some come in your index.js file


var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || 'myMasterKey',
  fileKey: 'optionalFileKey',
  serverURL: 'http://localhost:1337/parse' // Don't forget to change to https if needed
});


I had to add this two lines

  fileKey: 'optionalFileKey',
  serverURL: 'http://localhost:1337/parse' // Don't forget to change to https if needed

**Comment by lkf20** [comment] 2016-03-25 00:27
Sorry for my delay - thanks @michaelbina for the help!

**Comment by lkf20** [comment] 2016-03-25 05:25
It seems that in Parse Server v. 2.2.2 there is now an entirely separate module for the S3 adapter https://github.com/parse-server-modules/parse-server-s3-adapter/blob/master/package.json

Does anyone know how to use this with Heroku and the Parse Server Example?  The Parse Server Example, by the way, still only references v. 2.2.0

**Comment by Skyb0rg** [comment] 2019-01-22 18:57
I had the same issue today with localdatastore. only remove and new Install of the app was the solution. 
if i tried to save any pfobject -> code 151.
getting local results -> none
internet results readable.
writing new or updating pfobject with user Pointer -> Error 151 Can't upload a file that doesn't exist locally.

**Comment by koyinusa** [comment] 2019-04-28 09:48
Hi @Skyb0rg Were you able to get a fix for this issue.
